### ISSUE TITLE
CONFORMACION DEL EQUIPO

### ISSUE THREAD

**Issue by Elnenedelguion** [Elnenedelguion/MOD-PROGRAM-WEB-2024#26]

**Comment by Elnenedelguion** [comment]
Se conforma un grupo de 10 integrantes de distintas edades, género y nivel de conocimiento previo de manera de  potenciar el aprendizaje.

**Comment by Marilyn-hub** [comment]
En el grupo se promueve un ambiente colaborativo y comunicativo.
