### ISSUE TITLE
PUESTA EN MARCHA PROYECTO E-COMMERCE

### ISSUE THREAD

**Issue by Elnenedelguion** [Elnenedelguion/MOD-PROGRAM-WEB-2024#28]

**Comment by Elnenedelguion** [comment]
Informar enlace al repositorio en el formulario anterior y completar el documento IEEE830

**Comment by Elnenedelguion** [comment]
Posteriormente ese documento se enviara en  la Tarea 0 en el bloque de Actividades Integradoras del modulo correspondiente

**Comment by Elnenedelguion** [comment]
Se utilizara la gestión del tablero Kanban, Issues, Milestone y el code con branch necesarias.

**Comment by Elnenedelguion** [comment]
Se creara una Wiki organizada por Sprint y dentro de cada apartado el registro de las ceremonias.

**Comment by Marilyn-hub** [comment]
Las ceremonias contarán con un planning, daily, review y su retrospective idea board.
