### ISSUE TITLE
DESARROLLO PROYECTO E-COMMERCE

### ISSUE THREAD

**Issue by Elnenedelguion** [Elnenedelguion/MOD-PROGRAM-WEB-2024#29]

**Comment by Elnenedelguion** [comment]
Se definirá los roles de los miembros del equipo

**Comment by Elnenedelguion** [comment]
Plantear Historias de Usuarios en base a los requerimientos del proyecto

**Comment by Elnenedelguion** [comment]
Definir la documentación del proyecto mediante el documento IEEE830.

**Comment by Elnenedelguion** [comment]
Crear un proyecto estilo Kanban en GitHub.

**Comment by Elnenedelguion** [comment]
Definir la estructura de páginas en la Wiki del repositorio en GitHub

**Comment by Marilyn-hub** [comment]
Evaluar el contenido y distribución previa de la tienda para que se adecue al nuevo desarrollo de e-commerce / carrito de compras.
