### ISSUE TITLE
IMPLEMENTACION DEL FRONTEND

### ISSUE THREAD

**Issue by Marilyn-hub** [Elnenedelguion/MOD-PROGRAM-WEB-2024#33]
Se crea una aplicación SPA teniendo en cuenta el frontend estático completado en el módulo FullStack.
Se implementan los componentes: Landing page, dashboard, servicios, quienes somos, contacto y lo correspondiente a la gestión de usuarios.

**Comment by nataliaruiz04** [comment]
Se implementa el sistema de rutas (Routing) a fin de lograr la navegabilidad.

**Comment by Garaydiego** [comment]
se verifica la carpeta, todo ok!
